'use client';

import { ReactNode } from 'react';
import { usePathname } from 'next/navigation';
import ReduxProvider from '@/components/ReduxProvider';
import { AuthProvider } from '@/app/contexts/AuthContext';
import { ManagementProvider } from '@/app/contexts/ManagementContext';
import Header from '@/components/Header';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

interface LayoutProps {
  children: ReactNode;
}

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


export default function RootLayout({ children }: LayoutProps) {
  const pathname = usePathname();
  const isHomePage = pathname === '/';

  return (
    <html lang="en">
      <head>
        <title>Virpanix - Intelligent Real Estate Platform</title>
        <meta name="description" content="Modern co-working space management system" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.css" rel="stylesheet" />
        {/* <style>{`
    :root {
      --bs-primary: #000000;
      --bs-primary-rgb: 0, 0, 0;
      --bs-gradient: linear-gradient(135deg, #000000, #2b2b2b);
    }

    .btn-primary,
    .bg-primary {
      background-image: var(--bs-gradient);
      border-color: #000;
      transition: all 0.3s ease;
    }

    .btn-primary:hover {
      background-image: linear-gradient(135deg, #111, #525252ff);
      border-color: #525252ff;
    }
  `}</style> */}

      </head>
      <body suppressHydrationWarning={true}>
        <ReduxProvider>
          <AuthProvider>
            <ManagementProvider>
              {isHomePage}
              {children}
            </ManagementProvider>
          </AuthProvider>
        </ReduxProvider>
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
          crossOrigin="anonymous"
        />
      </body>
    </html>
  );
}
